---
title: "multilevel_pennies"
output: html_document
date: '2022-03-23'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("~/Documents/MASTERS_I_COGSCI/StudyGroupIdaTheaKiri")
library(pacman)
p_load(tidyverse, here, posterior, cmdstanr, boot, brms)
```


```{r}
data <- read.csv("penny_data/mp_schizophrenia.csv")

simple_reversal <- data[data$BotStrategy == 'SimpleReversal' & (data$Block == 1 | data$Block == 3), ]
simple_reversal <- na.omit(simple_reversal)


#Recoding variables
simple_reversal$win[simple_reversal$Payoff == 1 & lag(simple_reversal$Decision) == 1] <- 1
simple_reversal$win[simple_reversal$Payoff == 1 & lag(simple_reversal$Decision) == 0] <- -1
simple_reversal$win[simple_reversal$Payoff == -1] <- 0

simple_reversal$lose[simple_reversal$Payoff == -1 & lag(simple_reversal$Decision) == 1] <- -1
simple_reversal$lose[simple_reversal$Payoff == -1 & lag(simple_reversal$Decision) == 0] <- 1
simple_reversal$lose[simple_reversal$Payoff == 1] <- 0

simple_reversal<-simple_reversal[!(simple_reversal$Trial==1),]

```

```{r}
data1 <- na.omit(simple_reversal %>%
  subset(select=c(ID, Decision)) %>% 
  group_by(ID) %>%
  mutate(row = row_number()) %>% 
  pivot_wider(names_from = ID, values_from = Decision) %>%
  select(!(row)))

datawin <- na.omit(simple_reversal %>%
  subset(select=c(ID, win))%>% 
  group_by(ID) %>%
  mutate(row = row_number()) %>% 
  pivot_wider(names_from = ID,values_from = win)%>%
  select(!(row)))

datalose <- na.omit(simple_reversal %>%
  subset(select=c(ID, lose))%>% 
  group_by(ID) %>%
  mutate(row = row_number()) %>% 
  pivot_wider(names_from = ID,values_from = lose) %>%
  select(!(row)))


```


```{r}
data <- list(
    n = nrow(simple_reversal), 
    decision = as.matrix(data1),
    agents = length(names(data1)),
    win = as.matrix(datawin),
    lose = as.matrix(datalose))

```


```{r}
stan_file_simplereversal <- write_stan_file("
// This Stan model infers a rate (theta) from a number of trials (n) and successes (k)
// A function used for truncating SD later
functions {
  real normal_lb_rng(real mu, real sigma, real lb) {
    real p = normal_cdf(lb | mu, sigma); // cdf for bounds
    real u = uniform_rng(p, 1);
    return (sigma * inv_Phi(u)) + mu; // inverse cdf for value
  }
}


// The input data is two integer numbers: n and k.
data {
  int <lower=1> trials; // n of trials 
  int <lower=1> agents;
  array[trials, agents] int decision;  // choices
  array[trials, agents] int <lower=-1, upper=1> win; //stay bias
  array[trials, agents] int <lower=-1, upper=1> lose; //leave bias
}

// The parameters accepted by the model. Our model accepts only theta, the rate, 
// which is bound at 0 (no chances of success) and 1 (always success)
parameters {
  real alphaM;
  real <lower=0> alphaSD;
  real beta_stayM;
  real <lower=0> beta_staySD;
  real beta_leaveM;
  real <lower=0> beta_leaveSD;
  array[agents] real alpha;
  array[agents] real beta_stay;
  array[agents] real beta_leave;
}




// The model to be estimated; prior and likelihood
model {
  // The prior for theta is a uniform distribution between 0 and 1
  target += normal_lpdf(alphaM | 0, 1);
  target += normal_lpdf(alphaSD | 0, .3) - normal_lccdf(0| 0, .03);
  target += normal_lpdf(beta_stayM | 0, 0.3);
  target += normal_lpdf(beta_staySD | 0, 0.3)- normal_lccdf(0| 0, .03);
  target += normal_lpdf(beta_leaveM | 0, 0.3);
  target += normal_lpdf(beta_leaveSD | 0, 0.3)- normal_lccdf(0| 0, .03);

  // The model consists in a binomial distribution with a rate theta, 
  // and a number of trials n generating k successes
  target += bernoulli_logit_lpmf(alpha | alphaM, alphaSD);
  target += bernoulli_logit_lpmf(beta_stay | beta_stayM, beta_staySD);
  target += bernoulli_logit_lpmf(beta_leave | beta_leaveM, beta_leaveSD);

  for (i in 1:agents)
    target += bernoulli_logit_lpmf(decision[,i] | alpha[i] + to_vector(win[,i]*beta_stay[i] ) + to_vector( lose[,i]*beta_leave[i] ));
}

// This block quantifies the 
generated quantities{
  real alphaM_prior; 
  real<lower=0> alphaSD_prior; 

  real beta_stayM_prior; 
  real<lower=0> beta_staySD_prior;

  real beta_leaveM_prior; 
  real<lower=0> beta_leaveSD_prior;

  real alpha_prior; 
  real beta_stay_prior;
  real beta_leave_prior;

  array[trials,agents] int<lower=0, upper = trials> prior_preds;
  array[trials,agents] int<lower=0, upper = trials> posterior_preds; 

  alphaM_prior = normal_rng(0,1); 
  alphaSD_prior = normal_lb_rng(0,0.3,0); 
  beta_stayM_prior = normal_rng(0,1); 
  beta_staySD_prior = normal_lb_rng(0,0.3,0);
  beta_leaveM_prior = normal_rng(0,1); 
  beta_leaveSD_prior = normal_lb_rng(0,0.3,0);

  alpha_prior = inv_logit(normal_rng(alphaM_prior, alphaSD_prior)); 
  beta_stay_prior = normal_rng(beta_stayM_prior, beta_staySD_prior);
  beta_leave_prior = normal_rng(beta_leaveM_prior, beta_leaveSD_prior);

  for (i in 1:agents) 
    prior_preds[,i] = binomial_rng(trials, inv_logit(alpha_prior + to_vector(win[,i]) * beta_stay_prior) + inv_logit(to_vector(lose[,i]) * beta_leave_prior));

  for (i in 1:agents) 
    posterior_preds[,i] = binomial_rng(trials, inv_logit(alpha[i] + to_vector(win[,i]) * beta_stay[i]) + inv_logit(to_vector(lose[,i]) * beta_leave[i]));

} 


")
```


//transformed parameters{
//  vector[n] theta;
//  theta = alpha + (beta_stay*win)+ (beta_leave*lose); //multiplying the paramaters we want to estimate on the data
//}

```{r}

mod <- cmdstan_model(stan_file_simplereversal, cpp_options = list(stan_threads = TRUE), pedantic = TRUE)

```



